#!/bin/bash
# 
# Script for invoking CMake using the above CMakeLists.txt.  Invoke
# this script in the source directory containing CMakeLists.txt:
#
# $ ./do-configure
# $ make
#
# You will need to change the TRILINOS_PATH variable below to point to
# the location of your Trilinos install.  Other variables that you may
# need or want to change:
#
# CMAKE_BUILD_TYPE: "DEBUG" or "RELEASE".
#
# BUILD_SHARED_LIBS: If your build of Trilinos includes shared /
# dynamic libraries, you can save build time by linking against them
# instead of static libraries.  Otherwise, set this to OFF.
#
# CMAKE_VERBOSE_MAKEFILE: Set to ON if you prefer verbose Make output.
#

TRILINOS_INSTALL=/share/install/trilinos-12.11_gcc-6.1.0-openmpi-2.0.0
SRC=/home/jjellio3/src/trilinos-perf/SolverDriver

cmake \
  -G "Eclipse CDT4 - Unix Makefiles" \
  -D TRILINOS_PATH:FILEPATH="${TRILINOS_INSTALL}" \
  -D CMAKE_BUILD_TYPE:STRING=RELEASE \
  -D CMAKE_EXE_LINKER_FLAGS="-Wl,--allow-multiple-definition" \
${SRC}

#  -D CMAKE_EXE_LINKER_FLAGS="-Wl,--allow-multiple-definition" \

